export const GET_LINE2_DATA_REQUEST = "GET_LINE2_DATA_REQUEST";
export const GET_LINE2_DATA_SUCCESS = "GET_LINE2_DATA_SUCCESS";
export const GET_LINE2_DATA_FAILURE = "GET_LINE2_DATA_FAILURE";

export const GET_LINE3_DATA_REQUEST = "GET_LINE3_DATA_REQUEST";
export const GET_LINE3_DATA_SUCCESS = "GET_LINE3_DATA_SUCCESS";
export const GET_LINE3_DATA_FAILURE = "GET_LINE3_DATA_FAILURE";

export const GET_LINE4_DATA_REQUEST = "GET_LINE4_DATA_REQUEST";
export const GET_LINE4_DATA_SUCCESS = "GET_LINE4_DATA_SUCCESS";
export const GET_LINE4_DATA_FAILURE = "GET_LINE4_DATA_FAILURE";

export const GET_LINE5_DATA_REQUEST = "GET_LINE5_DATA_REQUEST";
export const GET_LINE5_DATA_SUCCESS = "GET_LINE5_DATA_SUCCESS";
export const GET_LINE5_DATA_FAILURE = "GET_LINE5_DATA_FAILURE";

export const GET_LINE6_DATA_REQUEST = "GET_LINE6_DATA_REQUEST";
export const GET_LINE6_DATA_SUCCESS = "GET_LINE6_DATA_SUCCESS";
export const GET_LINE6_DATA_FAILURE = "GET_LINE6_DATA_FAILURE";

export const GET_LINE7_DATA_REQUEST = "GET_LINE7_DATA_REQUEST";
export const GET_LINE7_DATA_SUCCESS = "GET_LINE7_DATA_SUCCESS";
export const GET_LINE7_DATA_FAILURE = "GET_LINE7_DATA_FAILURE";
